Added Environment variables discovery
preludeorg/community pull request #108
Opened 2021-04-08 18:44 UTC by wesley587

Identify all environment variables. Upon execution, environments variables and your path info will be displayed.

2021-04-12 21:36 UTC, wesley587 commented
@dkoch144 

I added you as an author too

2021-04-19 14:51 UTC, khyberspache requested changes

2021-04-19 14:51 UTC, khyberspache commented on discovery/1e68ef01-bdd1-4e51-b8b1-db02e935ecc3.yaml
> +  version: 2
Should be version 1

2021-04-19 17:47 UTC, wesley587 commented on discovery/1e68ef01-bdd1-4e51-b8b1-db02e935ecc3.yaml
> +  version: 2
@khyberspache 

Solved

2021-04-30 21:53 UTC, merged