Add "Find Kerberoastable Accounts" TTP
preludeorg/community pull request #125
Opened 2021-06-10 00:02 UTC by w0rk3r

2021-06-11 01:35 UTC, khyberspache requested changes
Nice. Minor comments, will need a spin up a windows domain to test on

2021-06-11 01:35 UTC, khyberspache commented on discovery/27b922c1-76ca-41c7-926f-1c36cabec122.yml
> +description: Find Accounts that might be vulnerable to Kerberoasting
Add a bit more detail here for new users that will look at this TTP.  Provide more details on what you're looking for specifically with this TTP (SPNs that can be abused, etc).  This is too similar to the name

2021-06-11 01:35 UTC, khyberspache commented on discovery/27b922c1-76ca-41c7-926f-1c36cabec122.yml
> +        - command: setspn.exe -T {discovery.domain} -Q */*
we have a parser that can find domains. Let's make this chain together with other TTPs. You're submitted other TTPs that do domain discovery, so find the technique number for one of those and do `#{domain.T1XXX}`

2021-06-11 01:35 UTC, khyberspache commented on discovery/27b922c1-76ca-41c7-926f-1c36cabec122.yml
> +        - command: setspn.exe -T {discovery.domain} -Q */*
also missing `#`

2021-06-11 01:35 UTC, khyberspache commented on discovery/27b922c1-76ca-41c7-926f-1c36cabec122.yml
> +        }
Have you tested this? Would the missing `;` cause any of these to no execute properly?

2021-06-11 02:05 UTC, w0rk3r commented on discovery/27b922c1-76ca-41c7-926f-1c36cabec122.yml
> +        }
![image](https://user-images.githubusercontent.com/26856693/121620241-5eac4d00-ca40-11eb-8ec6-7d0b48ab7649.png)

No problems here

2021-06-11 02:13 UTC, w0rk3r commented on discovery/27b922c1-76ca-41c7-926f-1c36cabec122.yml
> +        - command: setspn.exe -T {discovery.domain} -Q */*
Cool stuff

2021-06-11 02:20 UTC, w0rk3r commented on discovery/27b922c1-76ca-41c7-926f-1c36cabec122.yml
> +description: Find Accounts that might be vulnerable to Kerberoasting
Added

2021-06-15 17:01 UTC, w0rk3r commented
I think this one is ready to merge now @khyberspache

2021-06-15 17:29 UTC, khyberspache approved these changes

2021-06-15 17:31 UTC, merged