Adds "AWS Instance Metadata Discovery" TTP
preludeorg/community pull request #127
Opened 2021-06-10 00:39 UTC by w0rk3r

2021-06-11 01:47 UTC, khyberspache requested changes
The name on this TTP doesn't seem to match the TTP you're using. Can you clarify the name & description what you're trying to accomplish?

2021-06-11 01:47 UTC, khyberspache commented on discovery/4d5de7b1-4c9f-4a46-ae0b-1622bd6931e0.yml
> +name: AWS Instance Metadata Discovery
`Retrieve AWS instance metadata`

2021-06-11 01:47 UTC, khyberspache commented on discovery/4d5de7b1-4c9f-4a46-ae0b-1622bd6931e0.yml
> +description: Retrieve Instance Metadata for AWS Instances
Use this (https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html) to expand on this description (see my comments on your other pull requests)

2021-06-11 01:47 UTC, khyberspache commented on discovery/4d5de7b1-4c9f-4a46-ae0b-1622bd6931e0.yml
> +        Invoke-RestMethod -Uri http://169.254.169.254/latest/dynamic/instance-identity/document
This doesn't seem to match the name of the TTP. There is a specific metadata endpoint `http://169.254.169.254/latest/meta-data/` - this TTP is pulling the identity document (https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-identity-documents.html).

2021-06-11 02:29 UTC, w0rk3r commented on discovery/4d5de7b1-4c9f-4a46-ae0b-1622bd6931e0.yml
> +        Invoke-RestMethod -Uri http://169.254.169.254/latest/dynamic/instance-identity/document
Yeah man, sorry...Thanks for pointing it out! Fixed

2021-06-15 14:49 UTC, khyberspache approved these changes

2021-06-15 14:49 UTC, merged