Add "Request RC4 encrypted Kerberos TGS Service Ticket" TTP
preludeorg/community pull request #128
Opened 2021-06-11 01:19 UTC by w0rk3r

2021-06-11 01:53 UTC, khyberspache requested changes
You might be able to leverage parsers to automatically chain this with the SPN discovery TTP. Let's try to make that work

2021-06-11 01:53 UTC, khyberspache commented on credential-access/fd8f1dfe-9ab2-4a60-9f75-810472d9bb22.yml
> +        New-Object System.IdentityModel.Tokens.KerberosRequestorSecurityToken -ArgumentList '#{discover.spn}'
If you make this TTP use `ConvertTo-Json` in powershell or get it to format the data like `{'ServicePrincipalName': result}`, you can use the variable `#{json.T1087.002.ServicePrincipalName}` and this TTP will automatically get queued for any SPNs you discover.

2021-06-11 01:53 UTC, khyberspache commented on credential-access/fd8f1dfe-9ab2-4a60-9f75-810472d9bb22.yml
> +        New-Object System.IdentityModel.Tokens.KerberosRequestorSecurityToken -ArgumentList '#{discover.spn}'
Review my Azure TTPs for an example of how to use this.  Also the AWS TTPs will help you see how to chain these (I can show you)

2021-06-11 01:53 UTC, khyberspache commented on credential-access/fd8f1dfe-9ab2-4a60-9f75-810472d9bb22.yml
> +description: Retrieves RC4 encrypted Kerberos TGS for a given SPN
The name and description here are identical. The description should be a more verbose explanation of what's happening so newer people understand why they might need this

2021-06-15 14:58 UTC, khyberspache commented
@w0rk3r did you test to see if this chained properly with the `Find kerberoastable accounts`?

2021-06-15 15:22 UTC, w0rk3r commented
I've tested them individually, but I'm going to test it

2021-06-15 17:05 UTC, w0rk3r commented
Should be ready for merge now

2021-06-15 17:34 UTC, khyberspache approved these changes

2021-06-15 17:34 UTC, merged