Create d411d3c1-28eb-458c-b83a-70bfd4aa95a0.yml
preludeorg/community pull request #134
Opened 2021-06-19 03:05 UTC by 0xGotcha

UEFI Modified Windows Boot Loader

2021-06-19 04:49 UTC, 0xGotcha reviewed
Changed T&T to better fit the TTP. 

Adversaries may abuse Pre-OS Boot mechanisms as a way to establish persistence on a system. During the booting process of a computer, firmware and various startup services are loaded before the operating system. These programs control flow of execution before the operating system takes control.[1]

2021-06-19 16:40 UTC, 0xGotcha reviewed
removed tags line

2021-06-21 18:07 UTC, khyberspache commented
Assigning myself, will review tomorrow AM.

2021-06-22 22:53 UTC, khyberspache requested changes
small changes, I like this!

2021-06-22 22:53 UTC, khyberspache commented on persistence/d411d3c1-28eb-458c-b83a-70bfd4aa95a0.yml
> +  version: 1
add `tags: []`

2021-06-22 22:53 UTC, khyberspache commented on persistence/d411d3c1-28eb-458c-b83a-70bfd4aa95a0.yml
> +name: UEFI Modified Windows Boot Loader
Mount hidden EFI partition?

2021-06-24 00:28 UTC, 0xGotcha commented on persistence/d411d3c1-28eb-458c-b83a-70bfd4aa95a0.yml
> +name: UEFI Modified Windows Boot Loader
Technically you can remove it back after you mount yes.

2021-08-18 03:46 UTC, closed without merging