Create de5968fd-a075-4784-880e-a8709107ba3d.yml
preludeorg/community pull request #135
Opened 2021-06-19 04:41 UTC by 0xGotcha

2021-06-19 16:12 UTC, 0xGotcha reviewed
Changed naming convention to be more direct and removed a not needed line.

2021-06-21 18:07 UTC, khyberspache commented
Assigning myself, will review tomorrow AM.

2021-06-22 22:38 UTC, khyberspache requested changes
Questions/comments

2021-06-22 22:38 UTC, khyberspache commented on defense-evasion/de5968fd-a075-4784-880e-a8709107ba3d.yml
> +  version: 1
add a `destructive` tag here as it's installing new software:

```yaml 
metadata:
   authors:
     - Logical
   version: 1
   tags:
     - destructive
```

2021-06-22 22:38 UTC, khyberspache commented on defense-evasion/de5968fd-a075-4784-880e-a8709107ba3d.yml
> +name: 'EDR Visibility Abuse through WSL'
So this TTP is closer to installing WSL to avoid EDR in future commands I think?

Should the name be `Install WSL to enable EDR visibility abuse`

2021-06-22 22:38 UTC, khyberspache commented on defense-evasion/de5968fd-a075-4784-880e-a8709107ba3d.yml
> +        wsl --set-default-version 2
I ran this command as is on a fresh Win10Pro 21H1 with Elevated PSH:
<img width="785" alt="CleanShot 2021-06-22 at 18 37 24@2x" src="https://user-images.githubusercontent.com/43142871/123008463-e8391480-d388-11eb-80b5-60cc63568d4c.png">


Looks like it installed, but I can't set the version

2021-06-24 00:29 UTC, 0xGotcha commented on defense-evasion/de5968fd-a075-4784-880e-a8709107ba3d.yml
> +name: 'EDR Visibility Abuse through WSL'
Yeah this is what it aims for.

2021-06-24 00:29 UTC, 0xGotcha commented on defense-evasion/de5968fd-a075-4784-880e-a8709107ba3d.yml
> +        wsl --set-default-version 2
Likely requires a restart of powershell before running or the machine.

2021-07-28 13:42 UTC, w0rk3r commented on defense-evasion/de5968fd-a075-4784-880e-a8709107ba3d.yml
> +        wsl --set-default-version 2
![image](https://user-images.githubusercontent.com/26856693/127332525-5e0f889f-aa2b-4145-a07d-59038818c3c0.png)

Looks like it requires a restart of the machine, according to the docs https://docs.microsoft.com/en-us/windows/wsl/install-win10

2021-08-18 03:46 UTC, closed without merging