Adds Powershell Logging Disable Procedures
preludeorg/community pull request #136
Opened 2021-06-21 17:54 UTC by w0rk3r

2021-06-21 18:08 UTC, khyberspache commented
Assigning myself, will review tomorrow AM.

2021-06-22 22:21 UTC, khyberspache requested changes
I tried all three of these on a latest release of Win10Pro 21H1 and the reg key didn't exist

2021-06-22 22:21 UTC, khyberspache commented on defense-evasion/11c8c5a7-81d2-43af-8b87-42cba6259790.yml
> +  tags: []
Add a `-destructive` to all of these TTPs under the `tags`

2021-06-22 22:40 UTC, w0rk3r commented
All of them must be configured before in the Local Group Policy Editor, the keys don't exist if it is not configured

Before:
![image](https://user-images.githubusercontent.com/26856693/123008617-95178f80-d391-11eb-99d5-f74e70a92978.png)


After:
![image](https://user-images.githubusercontent.com/26856693/123008591-8630dd00-d391-11eb-9ebe-522d1c986cb8.png)

2021-06-22 22:41 UTC, w0rk3r commented on defense-evasion/11c8c5a7-81d2-43af-8b87-42cba6259790.yml
> +  tags: []
Done

2021-06-24 00:06 UTC, khyberspache approved these changes

2021-06-24 00:06 UTC, merged