Adds "Enumerate RDP Connection History" Procedure
preludeorg/community pull request #137
Opened 2021-06-21 20:42 UTC by w0rk3r

2021-06-21 20:43 UTC, w0rk3r commented
Ref: https://github.com/3gstudent/List-RDP-Connections-History

2021-06-22 22:27 UTC, khyberspache requested changes

2021-06-22 22:27 UTC, khyberspache commented on discovery/d03901f3-8061-4c55-880b-034886788e68.yml
> +            	Write-Host "User:"$User
We can probably set this up for future chaining if we somehow write it in JSON form here

2021-06-22 22:42 UTC, w0rk3r commented on discovery/d03901f3-8061-4c55-880b-034886788e68.yml
> +            	Write-Host "User:"$User
Going to take a look tomorrow

2021-06-29 14:35 UTC, w0rk3r commented on discovery/d03901f3-8061-4c55-880b-034886788e68.yml
> +            	Write-Host "User:"$User
![image](https://user-images.githubusercontent.com/26856693/123816964-245efe80-d8ce-11eb-8fa1-0c17bddb108d.png)

Done

2021-07-13 15:56 UTC, khyberspache approved these changes

2021-07-13 15:56 UTC, merged