Emoji Domain
preludeorg/community pull request #16
Opened 2020-11-23 21:34 UTC by savvyspoon

Tests if content control policies block emoji/puny code domains.

2020-11-23 21:38 UTC, khyberspache commented
Awesome contribution

2020-11-23 21:40 UTC, khyberspache commented on command-and-control/command_emoji_domain.yml
> +tactic: command-and-control
Exfiltration or C2 here? https://attack.mitre.org/techniques/T1041/ shows the tactic as `exfiltration`.

2020-11-23 21:41 UTC, privateducky commented on command-and-control/command_emoji_domain.yml
> +  tags:
Let's remove the tag, instead just use:
```
tags: []
```
We're not ready to drop in a new tag category yet-- but I'm going to mark this one (network) down, as I could see it being useful.

2020-11-23 21:44 UTC, privateducky commented on command-and-control/command_emoji_domain.yml
> +  Query an emoji domain to test if content control tools block access.  These domains can be used for typo squatting.
let's build out this description a bit. maybe this:

"Query an emoji domain to test if content control tools block access, as these domains are often used in typosquatting attacks. When used in a domain name, the browser uses “punycode” to convert the emojis into complicated strings like “xn--i-7iq.ws”, which are used to take users to the corresponding website."

2020-11-23 21:46 UTC, privateducky commented on command-and-control/command_emoji_domain.yml
> +  darwin:
we built a new shortcut for platforms which use the same command-- such as below. you can now use the "global" platform, such as:
```
platforms:
  global:
    sh:
      command: |
         curl xn--i-7iq.ws
```
This will cover both Darwin + Linux :)

2020-11-23 21:50 UTC, privateducky requested changes
Love the TTP. Couple minor tweaks then it's good to go!

2020-12-14 15:42 UTC, privateducky commented
@savvyspoon would love to get this in - it's a novel TTP which I think adds value. let me know if you need help w/any of the suggestions.

2020-12-14 22:49 UTC, savvyspoon commented
I'll get that done tonight

2020-12-15 04:56 UTC, savvyspoon commented
The file is have been updated. Please let me know if you need anything else

2020-12-15 12:28 UTC, privateducky approved these changes
great!

2020-12-15 12:28 UTC, merged