Adding various TTPS
preludeorg/community pull request #23
Opened 2020-12-15 17:25 UTC by bfuzzy1

TTPS include:

- Find unsecured credentials in files
- Disable macOS Gatekeeper
- Local network share discovery
- Sticky keys persistence

2020-12-15 17:38 UTC, khyberspache requested changes
Looks awesome.  Just providing some feedback and some questions. @privateducky will probably follow up with questions/comments too

2020-12-15 17:38 UTC, khyberspache commented on credential-access/740a8d86-cf25-4daf-9e66-0e5ffcb1042a.yml
> +    pwsh:
This the tag for powershell core, just an FYI in case you intended to use normal powershell `psh`

2020-12-15 17:38 UTC, khyberspache commented on defense-evasion/f0b13547-6f1a-418a-9331-ce08b0fed707.yml
> +  tags: []
let's add the tag `destructive` so that this isn't enabled by default

2020-12-15 17:38 UTC, khyberspache commented on credential-access/740a8d86-cf25-4daf-9e66-0e5ffcb1042a.yml
> +      command: 'grep -ri password #{file.path}'
discoverable variables/facts should follow the pattern `file.TECHNIQUE` like `#{file.T1005}`. The idea is that previous techniques would discover a file or directory. In this case you would probably want to use `directory.T1083` which would be directory paths discovered via File and Directory Discovery (https://attack.mitre.org/techniques/T1083/).

2020-12-15 17:38 UTC, khyberspache commented on credential-access/740a8d86-cf25-4daf-9e66-0e5ffcb1042a.yml
> +      command: 'grep -ri password #{file.path}'
Same as above comment

2020-12-15 17:38 UTC, khyberspache commented on persistence/f2963403-37a5-46e6-9cd5-f1c255012055.yml
> +        copy /Y #{agent.location} C:\Windows\System32\sethc.exe
Nice! Quick question here though; CMD/DOS doesn't respect line breaks in scripts as far as I knew (typically you have to use `&` to let run multiple commands). Will this work when an agent is tasked?  The agent would basically receive this entire block as a single string to execute

2020-12-15 18:23 UTC, privateducky commented on persistence/f2963403-37a5-46e6-9cd5-f1c255012055.yml
> +        copy /Y #{agent.location} C:\Windows\System32\sethc.exe
semi-colons may be needed

2020-12-15 18:24 UTC, privateducky commented on persistence/94f51428-4e71-4011-b634-674b7247e2ce.yml
> +  enabled: true
@khyberspache correct me if wrong-- but we don't need the enabled property on these, right? it gets appended by default.

2020-12-15 18:28 UTC, privateducky commented on persistence/f2963403-37a5-46e6-9cd5-f1c255012055.yml
> +  latest:
latest property can be removed (and enabled)

2020-12-15 18:30 UTC, privateducky commented on credential-access/740a8d86-cf25-4daf-9e66-0e5ffcb1042a.yml
> +      command: 'grep -ri password #{directory.T1083}'
remove quotes from this + linux grep command (not required, may cause issues)

2020-12-15 18:51 UTC, bfuzzy1 commented on persistence/f2963403-37a5-46e6-9cd5-f1c255012055.yml
> +        copy /Y #{agent.location} C:\Windows\System32\sethc.exe
Ooof. Correct! So, on my local instance I corrected it, but I am getting an error now: 

"C:\Windows\System32\config\systemprofile\AppData\Local\Microsoft\Windows\INetCache\Content.IE5\*: Access is denied"

Which I believe to be from the takeown command. I will reapproach this from the registry side.

2020-12-15 19:24 UTC, bfuzzy1 commented on credential-access/740a8d86-cf25-4daf-9e66-0e5ffcb1042a.yml
> +    pwsh:
I switched it thanks!

2020-12-15 19:24 UTC, bfuzzy1 commented on defense-evasion/f0b13547-6f1a-418a-9331-ce08b0fed707.yml
> +  tags: []
Added!

2020-12-15 19:25 UTC, bfuzzy1 commented on credential-access/740a8d86-cf25-4daf-9e66-0e5ffcb1042a.yml
> +      command: 'grep -ri password #{file.path}'
Updated to reflect

2020-12-15 19:29 UTC, bfuzzy1 commented on persistence/f2963403-37a5-46e6-9cd5-f1c255012055.yml
> +        copy /Y #{agent.location} C:\Windows\System32\sethc.exe
I changed this completely to be registry based. The above error was causing the TTP to be marked as incomplete in the platform even if everything went through. See [commit](https://github.com/preludeorg/community/pull/23/commits/497369c3446071f3727b9f0ebf89bdd3bc7cda1a)

2020-12-15 19:32 UTC, bfuzzy1 commented on credential-access/740a8d86-cf25-4daf-9e66-0e5ffcb1042a.yml
> +      command: 'grep -ri password #{directory.T1083}'
FYSA @privateducky the platform added them when I created through the editor.

2020-12-15 19:33 UTC, bfuzzy1 commented on credential-access/740a8d86-cf25-4daf-9e66-0e5ffcb1042a.yml
> +      command: 'grep -ri password #{file.path}'
Fixed that a removed those quotes the editor added.

2020-12-15 19:35 UTC, bfuzzy1 commented on persistence/f2963403-37a5-46e6-9cd5-f1c255012055.yml
> +  latest:
Done

2020-12-15 19:49 UTC, khyberspache commented on persistence/94f51428-4e71-4011-b634-674b7247e2ce.yml
> +  enabled: true
Yep - this can be removed as it's a derived property based upon the tags present

2020-12-15 19:55 UTC, khyberspache commented on credential-access/740a8d86-cf25-4daf-9e66-0e5ffcb1042a.yml
> +      command: 'grep -ri password #{directory.T1083}'
That makes sense... the yaml-dumper automatically adds quotes

2020-12-15 19:56 UTC, bfuzzy1 commented on persistence/94f51428-4e71-4011-b634-674b7247e2ce.yml
> +  enabled: true
I went ahead and removed

2020-12-15 20:50 UTC, bfuzzy1 commented on credential-access/740a8d86-cf25-4daf-9e66-0e5ffcb1042a.yml
> +      command: 'grep -ri password #{directory.T1083}'
Got it.

2020-12-15 22:39 UTC, privateducky approved these changes
This is good. Per Twitter, we may hit this password one with a v2 in the future. May require a little brain power on how best to search, remaining quiet...

2020-12-15 22:40 UTC, privateducky commented
ponging back to you @khyberspache, all good by my account. merge when ready.

2020-12-17 00:10 UTC, privateducky commented
@khyberspache bumping for you to confirm/deny

2020-12-19 04:40 UTC, khyberspache reviewed
One small tweak, but ready to go

2020-12-19 04:40 UTC, khyberspache commented on credential-access/740a8d86-cf25-4daf-9e66-0e5ffcb1042a.yml
> +        findstr /si pass *.xml *.doc *.txt *.xls
This will need a semicolon. I can add that when I merge tomorrow

2020-12-19 21:12 UTC, merged