Auth package
preludeorg/community pull request #271
Opened 2021-12-23 20:29 UTC by tr4cefl0w

Adding Authentication Package with payloads. Variant of the TTP contains the cleanup command. I did not want to put the cleanup commands in the base variant as doing the complete test requires the machine to reboot and check if Notepad runs as child process of lsass.exe

Payloads source can be found here:
https://github.com/tr4cefl0w/payloads/tree/master/T1547.002

2021-12-23 20:56 UTC, privateducky commented on payloads/config.yml
> +T1547.002:
ok, I see what you're doing here. instead of replacing this file's contents you'll want to add a new block to this file for your payload. so, essentially copy an existing block (like pneuma:) and paste it at the bottom of this file.

2021-12-23 21:03 UTC, privateducky commented on payloads/config.yml
> +T1547.002:
so your payload will look like this (just paste it at the bottom of config.yml)
```
T1547.002:
   metadata:
     description: Dropper and payload for T1547.002
     build: |
       dotnet publish -c Release -r win-x64
     platforms:
       - windows
   payloads:
     T1547.002: {}
```
How this works:
1. We'll fork your repository (at whatever commit you tell us) and review the code.
2. We'll add the repository to Community as a git submodule, so it'll show up in the payloads/src directory.
3. Once we do the above, your payload will automatically become available to all Operator users through our backend service which makes payloads (also TTPs, training modules and plugins) available to all users. When that happens, your payload will re-compile every hour by re-running the build script you put here.

2021-12-23 21:05 UTC, privateducky commented on payloads/config.yml
> +T1547.002:
This also means, you don't need to include the .dll and .exe files in this PR, as these will be built on our end before they get served to everyone else.

2021-12-23 21:06 UTC, privateducky requested changes
A couple of tweaks, otherwise this will be good to go. 

Note the instructions I left in the comments. You did a great job, considering our lack of extended docs around submitting payloads to Community. We'll definitely upgrade our docs around this because I know others have been wanting to do the same.

2021-12-24 02:53 UTC, tr4cefl0w commented on payloads/config.yml
> +T1547.002:
Hey thanks for the feedback. I wrongly assumed the config.yml should only contain what's needed (I figured what was there was just an example). I pushed the changes by appending the payload as you suggested. I also added the build command using some variables I saw in other payloads but I'm not sure I interpreted their usage properly.

Let me know if anything is missing. Note that package.c requires Visual Studio or at least MSBuild to build.

2022-01-04 16:04 UTC, privateducky commented on payloads/config.yml
> +T1547.002:
perfect. the last thing I see on this block to fix is the name of your payload. instead of using "T1547.002" as your payload name, you should choose your own custom name. for example, if you wanted to rename your payload "PolarBear" the config block would look like:
```
PolarBear:
   metadata:
     description: Dropper and payload for PolarBear
     build: |
       dotnet publish -c Release -r win-x64
     platforms:
       - windows
   payloads:
     PolarBear: {}
```
Also, don't forget to remove the .dll and .exe files from your PR.

2022-01-05 19:15 UTC, tr4cefl0w commented on payloads/config.yml
> +T1547.002:
Done

2022-01-06 12:51 UTC, privateducky commented
@khyberspache tossing this into your hands now. let me know if you want to talk through any of it.

2022-01-24 01:51 UTC, khyberspache approved these changes
Merging in to test in DEV

2022-01-24 01:51 UTC, merged