Added 9014f84a-ed8b-42e0-bda9-ac8c969f0d47
preludeorg/community pull request #273
Opened 2022-01-01 15:09 UTC by d4rk-d4nph3

I have a small question. I created this TTP from [this](https://unit42.paloaltonetworks.com/unit42-oilrig-targets-middle-eastern-government-adds-evasion-techniques-oopsie/) Unit 42's report.
Where do I have to put this reference link in the yaml file? For example, Sigma rule have a dedicated _reference_ field for this purpose.

2022-01-04 14:38 UTC, khyberspache requested changes
This is a solid TTP contribution! Just 2 very minor items then I will merge your submission, thanks!

2022-01-04 14:38 UTC, khyberspache commented on ttps/discovery/9014f84a-ed8b-42e0-bda9-ac8c969f0d47.yml
> +  name: System Checks
Change this to:
`name: 'Virtualization/Sandbox Evasion: System Checks'`

2022-01-04 14:38 UTC, khyberspache commented on ttps/discovery/9014f84a-ed8b-42e0-bda9-ac8c969f0d47.yml
> +  version: 1
Delete this, not needed anymore

2022-01-04 15:37 UTC, d4rk-d4nph3 commented on ttps/discovery/9014f84a-ed8b-42e0-bda9-ac8c969f0d47.yml
> +  version: 1
All three lines?

2022-01-04 15:42 UTC, d4rk-d4nph3 commented on ttps/discovery/9014f84a-ed8b-42e0-bda9-ac8c969f0d47.yml
> +  name: System Checks
I had wondered what to use here. I looked at other TTPs, and found they only mentioned the sub-technique part. 
But, I agree that putting the whole seems to be more informative.

2022-01-13 05:54 UTC, d4rk-d4nph3 commented on ttps/discovery/9014f84a-ed8b-42e0-bda9-ac8c969f0d47.yml
> +  version: 1
Okay.

2022-01-19 01:51 UTC, Xanthonus approved these changes

2022-01-24 01:42 UTC, khyberspache approved these changes

2022-01-24 01:42 UTC, merged