update pneuma configuration using keyword executor
preludeorg/community pull request #30
Opened 2021-01-12 22:34 UTC by khyberspache

2021-01-14 16:23 UTC, privateducky commented on command-and-control/23c5cb2f-3f6f-4770-b260-13edf23f5903.yml
> +  Pneuma is an open-source agent which accompanies the Prelude platform. This procedure sends an instruction to update the
change description to generic (Non-Pneuma) and let's do variations per agent that we have config swapping for (pneuma lol)

2021-01-14 16:24 UTC, privateducky commented on command-and-control/23c5cb2f-3f6f-4770-b260-13edf23f5903.yml
> +      command: 'config.{"Contact": "udp", "Address": "0.0.0.0:4545", "Sleep": 10}'
can we remove the ' quotes..? I don't think they're necessary..?

2021-01-14 16:24 UTC, privateducky requested changes
small things

2021-01-20 20:58 UTC, khyberspache commented on command-and-control/23c5cb2f-3f6f-4770-b260-13edf23f5903.yml
> +      command: 'config.{"Contact": "udp", "Address": "0.0.0.0:4545", "Sleep": 10}'
They are necessary otherwise yaml breaks

2021-01-20 23:05 UTC, privateducky approved these changes

2021-01-20 23:05 UTC, merged