added documentation for adding facts
preludeorg/community pull request #346
Opened 2022-02-15 22:26 UTC by seijisakurai

2022-02-15 22:27 UTC, privateducky commented on docs/operator/advanced/api.md
> +curl -X POST -sk -H 'Authorization:blue' "https://localhost:8888/v1/agents/privateducky/facts" -d '[{"key":"hello", "value":"world", "scope":"agent"},{"key":"fourth"}]' -H 'Content-Type: application/
describe that "privateducky" is the agent in this case.

also make the Authorization header consistent across all API examples in this doc.

2022-02-15 22:31 UTC, seijisakurai commented on docs/operator/advanced/api.md
> +curl -X POST -sk -H 'Authorization:blue' "https://localhost:8888/v1/agents/privateducky/facts" -d '[{"key":"hello", "value":"world", "scope":"agent"},{"key":"fourth"}]' -H 'Content-Type: application/
done

2022-02-15 22:55 UTC, privateducky commented on docs/operator/advanced/api.md
> +curl -X POST -sk -H $TOKEN "https://localhost:8888/v1/agents/agent_name/facts" -d '[{"key":"hello", "value":"world", "scope":"agent"},{"key":"fourth"}]' -H 'Content-Type: application/json'
good. now you need to replace all instances of $TOKEN in this file with "Authorization: $TOKEN"

2022-02-15 23:16 UTC, seijisakurai commented on docs/operator/advanced/api.md
> +curl -X POST -sk -H $TOKEN "https://localhost:8888/v1/agents/agent_name/facts" -d '[{"key":"hello", "value":"world", "scope":"agent"},{"key":"fourth"}]' -H 'Content-Type: application/json'
In the document it is mentioned that users need to replace $TOKEN with "Authorization: YOURTOKEN". Should we still replace them?

2022-02-15 23:22 UTC, privateducky commented on docs/operator/advanced/api.md
> +curl -X POST -sk -H $TOKEN "https://localhost:8888/v1/agents/agent_name/facts" -d '[{"key":"hello", "value":"world", "scope":"agent"},{"key":"fourth"}]' -H 'Content-Type: application/json'
I think I'd say something like: you must also pass in an authentication header like this... 

Then you can remove $token from all examples

2022-02-15 23:55 UTC, seijisakurai commented on docs/operator/advanced/api.md
> +curl -X POST -sk -H $TOKEN "https://localhost:8888/v1/agents/agent_name/facts" -d '[{"key":"hello", "value":"world", "scope":"agent"},{"key":"fourth"}]' -H 'Content-Type: application/json'
Went ahead with replacing the instances with "Authorization: YOUR_API_TOKEN".

2022-02-15 23:57 UTC, privateducky requested changes
Haha almost!

Going this direction, change YOUR_TOKEN back to $TOKEN so people can set an env variable then just copy this command.

2022-02-16 16:20 UTC, privateducky approved these changes

2022-02-16 16:20 UTC, merged