MacOS credential access and defense evasion
preludeorg/community pull request #35
Opened 2021-01-26 18:04 UTC by bfuzzy1

- Adding keychain dump
- Adding disable security updates (MacOS)
- Adding MacOS credential prompt

2021-01-26 23:56 UTC, privateducky approved these changes
Solid. Deferring to @khyberspache for final merge.

2021-01-28 17:03 UTC, khyberspache requested changes
A few questions but looks good overall

2021-01-28 17:03 UTC, khyberspache commented on credential-access/5c90420e-7972-4125-833b-16c89d5c303f.yml
> +      command: >-
We actually have the boiler plate for supporting osascript directly. We could probably add that in fairly easily, but it wouldn't know if we could write to file that way.

Something like this:
https://github.com/preludeorg/pneuma/pull/35

Thoughts?

2021-01-28 17:03 UTC, khyberspache commented on defense-evasion/4c9a443f-796d-4b79-a452-9c68ec85188a.yml
> +        defaults write /Library/Preferences/com.apple.SoftwareUpdate.plist
Do we need a semicolon at the end of this line, or even better an `&&`?

2021-01-28 17:20 UTC, bfuzzy1 commented on defense-evasion/4c9a443f-796d-4b79-a452-9c68ec85188a.yml
> +        defaults write /Library/Preferences/com.apple.SoftwareUpdate.plist
This should run without issue as long as it's being ran from an elevated context. Not sure why it was parsed as two lines, but I just tested the same yaml in Operator with no issues on my end.

2021-01-28 17:20 UTC, bfuzzy1 commented on credential-access/5c90420e-7972-4125-833b-16c89d5c303f.yml
> +      command: >-
Good point. I'm testing this out now on my end.

2021-01-28 18:29 UTC, bfuzzy1 commented on credential-access/5c90420e-7972-4125-833b-16c89d5c303f.yml
> +      command: >-
Removed bash version and added new osa executor on this one!

2021-01-28 20:10 UTC, khyberspache approved these changes

2021-01-28 20:10 UTC, merged