Removed variant IDs
preludeorg/community pull request #365
Opened 2022-02-23 21:23 UTC by seijisakurai

2022-02-23 22:29 UTC, privateducky commented on ttps/credential-access/6044fb78-5d7b-43cc-9592-dcba3c4537f1.yml
> +      command: dscl . read
why is this ttp different?

2022-02-23 22:30 UTC, privateducky commented on ttps/discovery/27b922c1-76ca-41c7-926f-1c36cabec122.yml
> -      - command: setspn.exe -T #{domain.T1018} -Q */*
another different TTP

2022-02-23 22:30 UTC, privateducky requested changes
stopping my review at 2 TTPs: there's more here than just ID removals, so do a pass through and see if you can catch any non ID changes

2022-02-23 23:17 UTC, seijisakurai commented
It seems like ruamel doesn't like it when you introduce hashtags that aren't double quoted. This is evident from the fact that double quoted facts don't break the unmarshalling. I will manually fix these.

2022-02-24 18:33 UTC, privateducky approved these changes

2022-02-24 18:33 UTC, merged