add dridex discovery TTP
preludeorg/community pull request #43
Opened 2021-02-04 03:09 UTC by clr2of8

2021-02-04 12:22 UTC, privateducky commented on discovery/be674970-449b-4eb6-95c3-251ee90bea69.yml
> +      command: 'ipconfig /all & whoami /all & nslookup -type=any #{domainname}'
@khyberspache this would fall into our custom variable format, as it's self-defined. deferring to you on variable syntax.

2021-02-04 12:23 UTC, privateducky approved these changes
Looks good to me; adds a new adversary tag, which is nice. @khyberspache can have the final look.

2021-02-04 12:24 UTC, privateducky commented on discovery/be674970-449b-4eb6-95c3-251ee90bea69.yml
> +tactic: discovery
Let's make this more generic on the name/description, as the tag will collect them under dridex. Maybe:
```
name: General discovery
description: A small set of reconnaissance commands often run in tandem 
```

2021-02-04 12:25 UTC, privateducky requested changes
i lied-- one request around name/description

2021-02-04 20:29 UTC, khyberspache commented on discovery/be674970-449b-4eb6-95c3-251ee90bea69.yml
> +      command: 'ipconfig /all & whoami /all & nslookup -type=any #{domainname}'
Well it could be custom like `#{discovery.local.existing.domain}` or `#{discovery.remote.domain}`.

It could also be found automatically with `#{domain.TXXX}` from a TTP that would generate a domain fact using this parser: 
```
  domain:
    regex:
      - ([\w]+\.(?:com|edu|org|net|io|mil|gov|de|ru|co.uk|co.au|cn|ru|info))
```

2021-02-07 12:26 UTC, privateducky commented on discovery/be674970-449b-4eb6-95c3-251ee90bea69.yml
> +      command: 'ipconfig /all & whoami /all & nslookup -type=any #{domainname}'
@clr2of8 just so you understand the difference, you can leave ```#{domainname}``` which will need to be manually filled in before running the TTP or you can use ```#{domain.TXXX}``` (specifying a technique) which will insert a domain found from running a TXXX procedure prior to this one.

2021-02-10 01:31 UTC, clr2of8 commented on discovery/be674970-449b-4eb6-95c3-251ee90bea69.yml
> +      command: 'ipconfig /all & whoami /all & nslookup -type=any #{domainname}'
thanks, I'll leave it for now

2021-02-17 15:08 UTC, merged