dont error and die if missing sliver certs
preludeorg/community pull request #497
Opened 2022-05-18 00:52 UTC by makk94

Goes with https://github.com/preludeorg/operator/pull/3893 which will display the chat messages for those on operator/not redirectors

2022-05-18 01:00 UTC, privateducky reviewed
do we want to uninstall the plugin on this error, or fail gracefully? 

I was anticipating a change in the operator source code for this, which is if a plugin initialize fails (plugin.js) then the plugin wouldn't load.

thoughts?

2022-05-18 01:14 UTC, makk94 commented
I had trouble making the change in operator. The error is thrown within a promise in Sliver, so I think the error is technically thrown after that eval() and isn't being caught by the try-catch() around the eval() in plugin.js ([here](https://github.com/preludeorg/operator/blob/master/static/js/objects/plugin.js#L57))

2022-05-18 01:28 UTC, privateducky commented
you might be right. I may just need to "feel" this one. let's screen share tomorrow.

2022-05-18 09:41 UTC, khyberspache requested changes
This change would make the plugin unusable; we have to install it first, then add the certificates, then the plugin reloads. 

We don't have a graceful way to have settings for plugins so this is hacky (for now). 

Once we upgrade the plugin to be a sliver client, this issue will persist.

2022-05-18 09:53 UTC, makk94 commented
Oh, because the certs have to be added to the plugins folder

Is killing headless when there's no cert necessary b/c the user needs to restart to get the plugin to reload? Or can we just return instead of erroring out when the cert isn't there?

2022-05-18 11:49 UTC, privateducky commented
@makk94 the recording of an error and skipping on this error sounds like the best approach.

2022-05-18 12:59 UTC, makk94 commented
Do you still want to try to find a way to skip the error on the Core side or just update this plugin?

2022-05-18 13:13 UTC, privateducky commented
> Do you still want to try to find a way to skip the error on the Core side or just update this plugin?

Question: is this an issue for any plugin that throws an exception? If so, we should handle via core code. Otherwise, if it's really just a sliver plugin type of thing, fixing here would be fine.

2022-05-18 15:04 UTC, makk94 commented
Could be an issue for any plugin that throws an error, though right now this is the only instance

Options I see (which all require cooperation from plugin code):

- plugins should never throw errors, they should just return early. We can add a new event or use chat:message event if Core needs to log something/do extra work
- we add some sort of global exception handler to Core and react to specific Errors in specific ways. Plugin must throw the right exception/ provide enough Error data that Core knows what to do with it
- plugins  have synchronous init() methods so that Plugin.js can catch the errors

Or we just keep letting plugins throw errors which kill headless, and we just add better logging

2022-05-18 23:31 UTC, privateducky commented on plugins/Sliver/Sliver.js
> -                    throw new Error(e);
because it'll crash the plugin, per @khyberspache's comment

2022-05-18 23:33 UTC, privateducky commented on plugins/Sliver/Sliver.js
> -                    throw new Error(e);
specifically, calling destroy will delete the plugin if you're missing the certificate, vs just skip loading it. 
although now that I write that.. maybe that's ok, as this would only happen on the SECOND load of the plugin, not the original installation. and if the cert isn't there in that case, who cases if we uninstall?

@khyberspache ok, can you spot check my logic.

2022-05-19 12:51 UTC, khyberspache commented on plugins/Sliver/Sliver.js
> -                    throw new Error(e);
The code here looks fine to me

2022-05-19 13:21 UTC, privateducky approved these changes

2022-05-19 13:21 UTC, merged