Create ttp [Retrieve in Memory Passwords]
preludeorg/community pull request #51
Opened 2021-02-05 07:21 UTC by abhiabhi2306

This technique can be used to retrieve passwords from the main memory character device image file (/dev/mem)

2021-02-05 16:55 UTC, khyberspache requested changes

2021-02-05 16:55 UTC, khyberspache commented on discovery/0e016565-f44f-4735-bfec-b714b87ee4b7.yml
> +name: Retrieve in Memory Passwords.
remove the period and lowercase `memory passwords`

2021-02-05 17:19 UTC, abhiabhi2306 commented
Oops, sorry, thank you for bringing that to my attention, rectified!

Kind Regards,
Abhi

2021-02-08 16:50 UTC, khyberspache requested changes

2021-02-08 16:50 UTC, khyberspache commented on discovery/0e016565-f44f-4735-bfec-b714b87ee4b7.yml
> +technique:
missing tactic

2021-02-08 17:53 UTC, abhiabhi2306 commented
Fixed, thank you ^^

2021-02-10 15:22 UTC, khyberspache approved these changes

2021-02-10 15:23 UTC, merged