perform data shredding
preludeorg/community pull request #52
Opened 2021-02-05 17:37 UTC by abhiabhi2306

This will perform shredding on C:/ drive on the deleted data and overwrite that making it impossible to recover the deleted data, this is helpful in scenarios where you need to make deleted data unrecoverable.

2021-02-05 17:57 UTC, w0rk3r reviewed
@abhiabhi2306 I think you meant `cipher` instead of `ciper`

2021-02-05 17:57 UTC, w0rk3r commented on execution/c9127250-9ec7-4d6c-b673-028a6191cbf9.yml
> +      command: ciper /w:C:\
@abhiabhi2306 I think you meant `cipher` instead of `ciper`

2021-02-05 17:59 UTC, abhiabhi2306 commented
Oops, typo! 


Fixed, thank you.

2021-02-07 12:12 UTC, privateducky requested changes
let's add a tag of "destructive" to this, which will disable the TTP by default. This is a simple protective measure we use to ensure a user doesn't accidentally bork themselves.

2021-02-07 12:18 UTC, abhiabhi2306 commented
> let's add a tag of "destructive" to this, which will disable the TTP by default. This is a simple protective measure we use to ensure a user doesn't accidentally bork themselves.

Yes, thats right, added.

Thank you

2021-02-08 16:49 UTC, khyberspache requested changes

2021-02-08 16:49 UTC, khyberspache commented on execution/c9127250-9ec7-4d6c-b673-028a6191cbf9.yml
> +    - Destructive
lowercase for consistency

2021-02-08 16:49 UTC, khyberspache commented on execution/c9127250-9ec7-4d6c-b673-028a6191cbf9.yml
> +technique:
Missing `tactic`

Lets change this TTP to a technique in the impact tactic

2021-02-08 17:56 UTC, abhiabhi2306 commented
added tactic, and changed path.

thank you :)

2021-02-10 15:26 UTC, khyberspache requested changes

2021-02-10 15:26 UTC, khyberspache commented on impact/c9127250-9ec7-4d6c-b673-028a6191cbf9.yml
> +    - Destructive
lowercase for consistency

2021-02-10 15:26 UTC, khyberspache commented on impact/c9127250-9ec7-4d6c-b673-028a6191cbf9.yml
> +  name: Command and Scripting Interpreter
lets make this:
```
id: T1485
name: Data Destruction
```

2021-02-10 16:03 UTC, abhiabhi2306 commented
Done, thank you :)

2021-02-11 00:29 UTC, merged