WIP: add core training module
preludeorg/community pull request #525
Opened 2022-07-03 14:23 UTC by makk94

2022-07-03 22:33 UTC, privateducky commented on training/introduction/core/a51a9dfb-c23e-4bea-8b98-fe1e22690592.yml
> +  script: Number($('#answer').val() === "5" || $('#answer').val() === "50")
this script doesn't look right

2022-07-03 22:36 UTC, privateducky commented on training/introduction/core/bba24f1c-eeac-4ba7-99b7-677af945ca90.yml
> +            return l.ttp.toLowerCase() === $('#answer').val().toLowerCase()
this is matching on the TTP ID, not the Link ID, which is what we should be looking for. I can see the question text may be confusing though, so maybe we should update that too.

2022-07-03 22:36 UTC, privateducky commented on training/introduction/core/c222c564-f61b-443a-9e9b-08ca7d585fc6.yml
> +  value: ATT&CK
this isn't right..

2022-07-03 22:38 UTC, privateducky commented on training/introduction/core/c222c564-f61b-443a-9e9b-08ca7d585fc6.yml
> +  According to its man page, one common variation for the TTP named 'Find recent files' is to vary the __ by which an
with the docs moving out of the app and into readme.com.. I'd add the new URL (docs.prelude.org) to the resource links - and update this flag to find something TTP-related in those docs. I'd stay away from the man pages though, as those will be changing ahead of 2.0, likely to TTP safety information.

2022-07-03 22:39 UTC, privateducky commented on training/introduction/core/e4d1529b-fd18-429c-ad6b-abbaa9b644f2.yml
> +  script: Number(Object.values(Attack.a).filter(atk => atk.name.toLowerCase() === 'my first ttp').length > 0)
script not checking for 'hello world'

2022-07-03 22:40 UTC, privateducky commented on training/introduction/core/ga095b52-db71-4c53-936d-80b64cf66495.yml
> +  script: Number($('#answer').val().toLowerCase().includes('conti') || $('#answer').val().toLowerCase().includes('kaseya'))
script won't work. 
we should update the challenge to not be as broad, but instead have the user hunt for a specific chain on chains.prelude.org to enter.

2022-07-03 22:40 UTC, privateducky commented on training/introduction/core/icf003b9-1db4-4d63-8897-efdc3d12f592.yml
> +  script: $('#answer').val().toLowerCase()
no good script

2022-07-04 18:17 UTC, makk94 commented on training/introduction/core/bba24f1c-eeac-4ba7-99b7-677af945ca90.yml
> +            return l.ttp.toLowerCase() === $('#answer').val().toLowerCase()
TTP ID is what I was aiming for - why do you prefer link id? I don't see link id displayed anywhere in operator.

Did update the question text to be even more explicit though

2022-07-04 18:44 UTC, makk94 commented on training/introduction/core/c222c564-f61b-443a-9e9b-08ca7d585fc6.yml
> +  According to its man page, one common variation for the TTP named 'Find recent files' is to vary the __ by which an
My goal was to draw attention to the man pages, I thought they were useful :) 
Being said, three options (in order of my preference):
- keep the general idea of focusing on the man pages and change the question whenever we change the man pages in 2.0
- ditch the question entirely
- change the question to one around using search filters for TTPs. Don't love it b/c it's just super similar to the 'understanding chains' challenge later on (which uses search filters but on chains)

or if you have another question in mind, lmk - there aren't many ttp-specific questions that _need_ the docs to be answered

2022-07-04 20:12 UTC, privateducky commented on training/introduction/core/bba24f1c-eeac-4ba7-99b7-677af945ca90.yml
> +            return l.ttp.toLowerCase() === $('#answer').val().toLowerCase()
Either works; as long as the text is clear

2022-07-05 09:47 UTC, makk94 commented on training/introduction/core/ga095b52-db71-4c53-936d-80b64cf66495.yml
> +  script: Number($('#answer').val().toLowerCase().includes('conti') || $('#answer').val().toLowerCase().includes('kaseya'))
I'd say a broader questions is better for teaching users to browse the chains website. If we just give the name of a specific chain to hunt for, they'll just copy paste it into the search bar and skip the interesting filter options

2022-07-05 10:45 UTC, privateducky commented on training/introduction/core/c222c564-f61b-443a-9e9b-08ca7d585fc6.yml
> +  According to its man page, one common variation for the TTP named 'Find recent files' is to vary the __ by which an
yeah.. these man pages will swap in format pretty soon, so I don't like leaning in yet... what about converting this flag into one about the 'keyword executor' as that's a generally unknown (and powerful) option?

2022-07-05 10:46 UTC, privateducky commented on training/introduction/core/d60a36e3-9256-4722-9f3e-157cfd17ff57.yml
> +  Locate the TTP named 'Find recent files' and write a variant for your platform that searches your /tmp (or TEMP)
seems if we have you write a variant, we should also have you execute the variant. 
to do this, the user needs to 'split' the TTP on the chain sidebar and ensure their variant remains in the list.

2022-07-05 10:48 UTC, privateducky commented on training/introduction/core/e4d1529b-fd18-429c-ad6b-abbaa9b644f2.yml
> +  Modern securities: |
in fact, this entire block is pretty hard to read. I like the message but can you make it more readable?

2022-07-05 10:52 UTC, privateducky commented on training/introduction/core/ga095b52-db71-4c53-936d-80b64cf66495.yml
> +  up often in the app: adversary and chain, so let's look at them a little closer. The term chain was originally used
this description doesn't help add context to the challenge. looks like an old description I wrote for 'what is a chain :)'

2022-07-05 10:52 UTC, privateducky commented on training/introduction/core/ga095b52-db71-4c53-936d-80b64cf66495.yml
> +  - Make sure you are looking at chains for your current license.
a couple of these hints won't help

2022-07-05 10:54 UTC, privateducky commented on training/introduction/core/jaca7e81-3855-452e-91b0-997fd42ead4b.yml
> +name: Continuous testing
good final flag to lead into the detect mindset

2022-07-05 10:54 UTC, privateducky requested changes
round of review done!

2022-07-05 20:34 UTC, makk94 commented on training/introduction/core/ga095b52-db71-4c53-936d-80b64cf66495.yml
> +  - Make sure you are looking at chains for your current license.
Which hint doesn't help?

2022-07-05 21:58 UTC, makk94 commented on training/introduction/core/c222c564-f61b-443a-9e9b-08ca7d585fc6.yml
> +  According to its man page, one common variation for the TTP named 'Find recent files' is to vary the __ by which an
I'll look into `keyword` and see what it is ha

In the meantime, do you think any of the block info (IOC, kill chain, att&ck) is crucial to keep? They don't sound like things that would tie in very well with a challenge on the keyword executor

2022-07-05 21:59 UTC, makk94 commented on training/introduction/core/d60a36e3-9256-4722-9f3e-157cfd17ff57.yml
> +  Locate the TTP named 'Find recent files' and write a variant for your platform that searches your /tmp (or TEMP)
updated the challenge and text, lmk if the text is too obvious/ instructional

2022-07-05 21:59 UTC, makk94 commented on training/introduction/core/e4d1529b-fd18-429c-ad6b-abbaa9b644f2.yml
> +  Modern securities: |
done

2022-07-05 22:00 UTC, makk94 commented on training/introduction/core/ga095b52-db71-4c53-936d-80b64cf66495.yml
> +  up often in the app: adversary and chain, so let's look at them a little closer. The term chain was originally used
this challenge is the intro to chains, so a description for 'what is a chain' should be pretty apt

Still, updated the text, lmk wyt

2022-07-05 22:00 UTC, makk94 commented on training/introduction/core/jaca7e81-3855-452e-91b0-997fd42ead4b.yml
> +name: Continuous testing
:)

2022-07-05 22:02 UTC, makk94 commented
@privateducky up for another round of reviews! Left a couple questions above, and haven't updated the keyword challenge yet (third challenge), but the rest are good to go for you

2022-07-06 21:01 UTC, privateducky commented on training/introduction/core/ga095b52-db71-4c53-936d-80b64cf66495.yml
> +  - Make sure you are looking at chains for your current license.
all but the last.
can't filter by theme.. or can you?
can't view chains that aren't in your license... or can you?

unless - this indicates you should check out chains.prelude.org to solve the puzzle? in that case, this works. it's a little subtle in terms of messaging that's how you solve it, but that's probably ok.

2022-07-06 21:08 UTC, makk94 commented on training/introduction/core/ga095b52-db71-4c53-936d-80b64cf66495.yml
> +  - Make sure you are looking at chains for your current license.
Yeah, this is meant to be solved on teh chains.prelude.org website. It's a little subtle, but since the link is right there in the Resources, and the first hint (first to show up to users, last in the yml) is very explicit, I don't think it's too subtle

2022-07-06 21:31 UTC, privateducky commented
@jpmoss @mireaulf can you answer @makk94 's question on CNAME?

2022-07-06 21:32 UTC, mireaulf commented
@makk94 the full url will be doc.prelude.org

2022-07-06 21:44 UTC, makk94 commented
Thanks - updated!

2022-07-07 00:36 UTC, jaherne commented on training/introduction/core/d60a36e3-9256-4722-9f3e-157cfd17ff57.yml
> +  - The variant ID should look something like `00010203-0405-0607-0809-0a0b0c0d0e0f:global:ls:0`
Is the only place to see the variant ID (in the form `00010203-0405-0607-0809-0a0b0c0d0e0f:global:ls:0`) by launching a new chain and then changing the view from TTP names to TTP identifiers? If so, I think a hint about the views button would be helpful.

2022-07-07 10:17 UTC, privateducky commented on training/introduction/core/d60a36e3-9256-4722-9f3e-157cfd17ff57.yml
> +  - The variant ID should look something like `00010203-0405-0607-0809-0a0b0c0d0e0f:global:ls:0`
you're both actually right. you can split a TTP to see the variants. you can also click the 'views' to see them.
<img width="674" alt="Screen Shot 2022-07-07 at 6 17 02 AM" src="https://user-images.githubusercontent.com/49954156/177750828-b3eed3c4-557f-40d4-9a60-2b6362d17bd6.png">

2022-07-07 10:18 UTC, privateducky commented on training/introduction/core/e4d1529b-fd18-429c-ad6b-abbaa9b644f2.yml
> +            return l.response.output.toLowerCase() === 'hello world'
we often get people tripped up on case, so may want to consider insensitivity

2022-07-07 10:20 UTC, privateducky approved these changes
this is good to me; will wait on @khyberspache and @jaherne 's review before merging.

2022-07-11 17:07 UTC, merged