Adding the ttp to find group hashes.
preludeorg/community pull request #53
Opened 2021-02-05 18:21 UTC by masterugwee

2021-02-06 05:53 UTC, masterugwee commented
One TTP can be used to display the group hashes from /etc/gshadow in Linux system. 
The second one can be used to display the list of groups from /etc/group.

2021-02-07 12:09 UTC, privateducky approved these changes
Awesome. On to @khyberspache for final approval.

2021-02-08 16:51 UTC, khyberspache requested changes

2021-02-08 16:51 UTC, khyberspache commented on discovery/83c991b4-5ff0-4fe5-80ab-c78737ccef61.yml
> +technique:
missing tactic

2021-02-08 16:51 UTC, khyberspache commented on discovery/8fc7de44-c830-47c9-b05b-b53b1352e874.yml
> +technique:
missing tactic.

2021-02-08 18:27 UTC, masterugwee commented on discovery/8fc7de44-c830-47c9-b05b-b53b1352e874.yml
> +technique:
Added tactic to both files.

2021-02-10 15:28 UTC, khyberspache commented
@masterugwee The TTPs look good, but it appears that you need to rebase because there are two extra TTPs in this PR that aren't up to date with master.  You can either:
1. Open a new PR with just the two YMLs you want to submit
2. Rebase your branch to master then repush

2021-02-10 15:28 UTC, khyberspache requested changes
see above comment

2021-02-10 16:35 UTC, masterugwee commented
> @masterugwee The TTPs look good, but it appears that you need to rebase because there are two extra TTPs in this PR that aren't up to date with master. You can either:
> 
>     1. Open a new PR with just the two YMLs you want to submit
> 
>     2. Rebase your branch to master then repush

I guess this solves it. Right.

2021-02-10 17:21 UTC, khyberspache commented
Merged your other PR

2021-02-10 17:21 UTC, closed without merging