Create 5b4a7cf6-6bcf-11eb-9439-0242ac130002.yml
preludeorg/community pull request #60
Opened 2021-02-10 18:44 UTC by abhiabhi2306

This command will display you all the network information you want in one go, this approach is less likely to trigger blueteam monitoring systems.

2021-02-11 00:37 UTC, khyberspache requested changes
Nice one!

2021-02-11 00:37 UTC, khyberspache commented on discovery/5b4a7cf6-6bcf-11eb-9439-0242ac130002.yml
> +name: Show whole network information
> Dump all network configuration data

2021-02-11 00:37 UTC, khyberspache commented on discovery/5b4a7cf6-6bcf-11eb-9439-0242ac130002.yml
> +  This command will display you all the network information you want in one go, this approach is less likely to trigger blueteam monitoring systems.
>  This command will display all of the system's network configuration information using an approach that is less likely to trigger blue-team monitoring systems.

2021-02-11 19:38 UTC, abhiabhi2306 commented
Done, thank you :)

2021-02-11 23:02 UTC, merged

2021-03-19 21:18 UTC, w0rk3r commented
@khyberspache this one got the tactic duplicated in the description