Pull Request
preludeorg/community pull request #62
Opened 2021-02-10 18:54 UTC by 231tr0n

2021-02-11 00:45 UTC, khyberspache requested changes
Small changes, great work!

2021-02-11 00:45 UTC, khyberspache commented on discovery/1bfcd55d-05e1-4404-a112-8c65cb4652fa.yml
> +name: List of all packages installed
> List all installed packages

2021-02-11 00:45 UTC, khyberspache commented on discovery/f1628a03-957d-4a0d-a97a-ffc271d5fae1.yml
> +name: View OS Properties
> View basic OS properties

We could add some simple windows stuff here in the future

2021-02-11 00:45 UTC, khyberspache commented on impact/a4e43c2e-0397-4633-9c13-849925fbc1cc.yml
> +  name: Home-Directory Deletion
```
id: T1485
name: Data Destruction
```

2021-02-11 00:45 UTC, khyberspache commented on impact/a4e43c2e-0397-4633-9c13-849925fbc1cc.yml
> +      command: rm -rf ~
We have a way to make this "global", so you can put:

```
platforms:
  global:
    sh:
      command: rm -rf ~
```

2021-02-11 00:45 UTC, khyberspache commented on impact/a4e43c2e-0397-4633-9c13-849925fbc1cc.yml
> +      command: rm -rf ~
And we use `darwin` instead of `Mac` in the future ;)

2021-02-11 00:45 UTC, khyberspache commented on impact/fa6c9066-e5cb-47ac-989e-d255c10f89f6.yml
> +name: Kill all the processes running on the machine
> Kill all running processes

2021-02-11 00:45 UTC, khyberspache commented on impact/fa6c9066-e5cb-47ac-989e-d255c10f89f6.yml
> +  name: Kill all processes
```
id: T1489
name: Service Stop
```

This probably fits better

2021-02-11 14:33 UTC, 231tr0n reviewed
Done all the changes you wanted

2021-02-11 14:42 UTC, 231tr0n reviewed
Please tell me if there are anymore changes to do

2021-02-11 17:09 UTC, khyberspache requested changes
Almost there!

2021-02-11 17:09 UTC, khyberspache commented on impact/a4e43c2e-0397-4633-9c13-849925fbc1cc.yml
> +      command: rm -rf ~
You can delete these, then I'll merge

2021-02-12 05:02 UTC, 231tr0n commented on impact/a4e43c2e-0397-4633-9c13-849925fbc1cc.yml
> +      command: rm -rf ~
done

2021-02-12 05:05 UTC, 231tr0n commented
Made those changes which you suggested

2021-02-12 21:56 UTC, merged