Adds the Capability of Enumerate Local Groups
preludeorg/community pull request #69
Opened 2021-02-11 01:25 UTC by w0rk3r

2021-02-23 14:34 UTC, khyberspache requested changes
very small changes

2021-02-23 14:34 UTC, khyberspache commented on discovery/d7add940-1137-4975-b7d5-cab9a107a6c6.yml
> +description: Retrieves all Local Groups
Retrieve local group information on the target system.

2021-02-23 14:34 UTC, khyberspache commented on discovery/d7add940-1137-4975-b7d5-cab9a107a6c6.yml
> +    - Powerview
We are going to keep tags empty for now on this repo unless myself/privateducky adds it. Make this 
`tags: []`

2021-02-23 17:59 UTC, w0rk3r commented
Fixed

2021-03-08 15:40 UTC, khyberspache approved these changes

2021-03-08 15:40 UTC, merged