TTP's for Defense Evasion and Credential Access
preludeorg/community pull request #79
Opened 2021-02-12 12:54 UTC by Abyss101

1. Disable Windows EventLog via MinNt Entry via Reg Command
2. Disable Windows EventLog via EventCleaner
3. Use of NTDS for Copying DC Database

2021-02-23 14:52 UTC, khyberspache requested changes
Very small tweaks. Excellent work!

2021-02-23 14:52 UTC, khyberspache commented on defense-evasion/8feb27ce-63db-472f-b8e9-038134e9d79a.yml
> +  tags: destructive
needs to be a list:

```yaml
tags:
  - destructive
```

2021-02-23 14:52 UTC, khyberspache commented on defense-evasion/e4209652-91f4-4c7b-8b5d-db246bb08764.yml
> +  tags: destructive
needs to be a list:

```yaml
tags:
  - destructive
```

2021-02-25 13:31 UTC, Abyss101 commented on defense-evasion/8feb27ce-63db-472f-b8e9-038134e9d79a.yml
> +  tags: destructive
Hello, done revision. 

Thank you

2021-02-25 13:31 UTC, Abyss101 commented on defense-evasion/e4209652-91f4-4c7b-8b5d-db246bb08764.yml
> +  tags: destructive
Hello, done revision. 

Thank you

2021-03-08 15:41 UTC, merged