create tap
preludeorg/community pull request #81
Opened 2021-02-12 19:20 UTC by anukaal

2021-02-23 15:04 UTC, khyberspache requested changes

2021-02-23 15:04 UTC, khyberspache commented on discovery/9fe853c0-2cd7-49dc-88b4-ccbc25029dd7.yml
> +  Linux distributions use the /etc/shadow file to store encrypted password data and can show the name of user .
> Linux distributions use the /etc/shadow file to store encrypted password data. You will also see names of all users on the system.

2021-02-23 15:04 UTC, khyberspache commented on discovery/9fe853c0-2cd7-49dc-88b4-ccbc25029dd7.yml
> +name: View the password data
View linux shadow file

2021-02-23 15:04 UTC, khyberspache commented on discovery/16fd2706-8baf-433b-82eb-8c7fada847da.yml
> +name: View the bashrc file
View system-wide bashrc configuration

2021-02-23 15:04 UTC, khyberspache commented on discovery/00010203-0405-0607-0809-0a0b0c0d0e0f.yml
> +name: View the hidden file
View hidden files in working directory

2021-02-23 15:04 UTC, khyberspache commented on discovery/00010203-0405-0607-0809-0a0b0c0d0e0f.yml
> +   ls -a in linux will show you the hidden files in your system.
> Use the ls tool to view all files (including hidden files) in the working directory

2021-02-28 13:12 UTC, anukaal commented
Done all the changes

2021-03-08 15:43 UTC, khyberspache requested changes

2021-03-08 15:43 UTC, khyberspache commented on discovery/00010203-0405-0607-0809-0a0b0c0d0e0f.yml
> +name: View the hidden file
Once this is changed, I can merge.

2021-03-08 17:16 UTC, anukaal commented on discovery/00010203-0405-0607-0809-0a0b0c0d0e0f.yml
> +name: View the hidden file
Done

2021-03-11 20:54 UTC, khyberspache approved these changes

2021-03-11 20:56 UTC, merged