AMSI Protection Providers Enumeration TTP
preludeorg/community pull request #82
Opened 2021-02-12 21:38 UTC by w0rk3r

Based on https://github.com/GhostPack/Seatbelt/blob/master/Seatbelt/Commands/Windows/AMSIProvidersCommand.cs

2021-02-23 15:04 UTC, khyberspache commented on discovery/221bc8bd-077f-41cb-bc14-f415442e7082.yml
> +    - Seatbelt
Remove the tags for now

2021-02-23 15:05 UTC, khyberspache requested changes
Small change, but approved

2021-02-23 15:05 UTC, khyberspache commented on discovery/221bc8bd-077f-41cb-bc14-f415442e7082.yml
> +    - Seatbelt
Remove the tags for now `tags: []`

2021-02-23 18:00 UTC, w0rk3r commented
Fixed

2021-03-08 15:44 UTC, khyberspache approved these changes

2021-03-08 15:44 UTC, merged