TTPs for shadowhashdata and enable root (macOS)
preludeorg/community pull request #91
Opened 2021-03-01 18:32 UTC by bfuzzy1

2021-03-11 21:00 UTC, khyberspache requested changes
Awesome-sauce my dude

2021-03-11 21:00 UTC, khyberspache commented on privilege-escalation/62933e77-9c3c-49be-9152-6990a654abf9.yml
> +      command: dsenableroot -u #{T1087.001} -p #{user.password.T1078} -r #{root.password.T1078}
`dsenableroot -u #{discovery.local.existing.user} -p #{discovery.local.existing.user.password} -r #{privilege-escalation.local.new.user.password}`

2021-03-11 21:10 UTC, bfuzzy1 commented
@khyberspache changes made!

2021-03-12 20:54 UTC, khyberspache approved these changes

2021-03-12 20:54 UTC, merged